{% set name = "jupyterlab-urdf" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_urdf-{{ version }}.tar.gz
  sha256: c17c642cc2ac7156c58dcb4f1d6d24f90c1c9d51173526e58cc8249f5529c305

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - jupyter-packaging
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - jupyterlab_urdf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ihuicatl/jupyterlab_urdf
  summary: A URDF viewer and editor extension for JupyterLab.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ihuicatl
