{% set name = "jupyterlab-urdf" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_urdf-{{ version }}.tar.gz
  sha256: 6063cb4c9f622e490cb7590294f8b90ce6ff9e858f0b4ebfcb082a8038ef2af4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - jupyter-packaging
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - jupyter-rospkg

test:
  imports:
    - jupyterlab_urdf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ihuicatl/jupyterlab_urdf
  summary: A URDF viewer and editor extension for JupyterLab.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ihuicatl
