{% set name = "jupyterlab-urdf" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_urdf-{{ version }}.tar.gz
  sha256: 1c180a5ca7a9b779fb6b39d91063bf015f04f4ed0c57fd363c8510f3c153e201

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
    - hatchling
    - nodejs
    - hatch-nodejs-version
    - hatch-jupyter-builder
  run:
    - python >=3.9

test:
  imports:
    - jupyterlab_urdf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jupyter-robotics/jupyterlab-urdf
  summary: A URDF viewer and editor extension for JupyterLab.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ihuicatl
