{% set name = "jupyterlab-urdf" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_urdf-{{ version }}.tar.gz
  sha256: 8b1a8f2f442fffcbb8a5a7d6acc686936219ec0bafc6d3205236fd77b0be390f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - jupyter-packaging
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - jupyter-rospkg

test:
  imports:
    - jupyterlab_urdf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ihuicatl/jupyterlab_urdf
  summary: A URDF viewer and editor extension for JupyterLab.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ihuicatl
